### PR TITLE
fix: fix syntax error in code snippet

### PR DESCRIPTION
**Pull request by ghassanmas**
**Description:**

Just fixing a syntax/typo in Readme

**JIRA:**

[XXX-XXXX](https://openedx.atlassian.net/browse/XXX-XXXX)

**Dependencies:**

List dependencies on other outstanding PRs, issues, etc.

**Merge deadline:**

List merge deadline (if any)

**Installation instructions:**

List any non-trivial installation
instructions.

**Testing instructions:**
Just replicate this:

> Then, open a shell using ``./manage.py lms shell`` and run::
```
>>> from django.apps import apps
>>> [app.verbose_name for app  in apps.get_app_configs()]
```
**Reviewers:**
- [ ] tag reviewer

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPi after tag-triggered build is
      finished.
- [ ] Delete working branch (if not needed anymore)

**Author concerns:**

List any concerns about this PR - inelegant
solutions, hacks, quick-and-dirty implementations, concerns about
migrations, etc.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @ghassanmas! I've created [OSPR-6498](https://openedx.atlassian.net/browse/OSPR-6498) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by ghassanmas** [comment]
This ready for review

**Review by robrap — APPROVED** [review]
Thanks.

**Comment by edx-webhook** [comment]
@ghassanmas 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/edx-django-utils&entry.867055334=https://github.com/openedx/edx-django-utils/pull/196&entry.1484655318=https://github.com/ghassanmas&entry.752974735=2022-03-02+10:25&entry.1917517419=2022-03-02+21:53&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
